### ISSUE TITLE
Documentation build error

### ISSUE THREAD

**Issue by droogmic** [therealprof/microbit#2]
See: 
https://docs.rs/crate/microbit/0.5.2/builds/105063

likely due to : https://users.rust-lang.org/t/psa-breaking-change-panic-fmt-language-item-removed-in-favor-of-panic-implementation/17875
```
error[E0658]: The attribute `panic_implementation` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/panic-abort-0.2.0/src/lib.rs:28:1
   |
28 | #[panic_implementation]
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable
```

**Comment by therealprof** [comment]
No, that's something else, `panic_implementation` *is* the new method...

**Comment by therealprof** [comment]
@droogmic FWIW, this is the origin of that error: https://docs.rs/crate/panic-abort/0.2.0/builds/102908

**Comment by droogmic** [comment]
Sorry, my bad. I guess we need to wait until japaric updates it.
