### ISSUE TITLE
Outdated dependency on nrf51-hal

### ISSUE THREAD

**Issue by Eragonfr** [therealprof/microbit#40]
The outdated dependency on nrf51-hal v0.7 is broking the use of others library based on more recent nrf51-hal versions.
It can be an issue for moving to [nrf-rs]( nrf-rs ) org like mentioned on other issue.

**Comment by therealprof** [comment]
@Eragonfr We're currently in the process of moving. That problem has been addressed already if you'd like to have a look at the latest commits.
